# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the type of runner to use

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3

      # Generates the snake  
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: MrpasswordTz  # Replace with your GitHub username
          outputs: |
            dist/github-snake.svg  # Output file path for the SVG

      # Show the status of the build for debugging
      - run: git status

      # Push the changes to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
          branch: output  # Specify the branch to push to
          force: true

      # Deploy to GitHub Pages (if needed)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The branch where the output will be pushed
          build_dir: dist  # Directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
